# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweepstake', '0004_auto_20180124_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
