# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweepstake', '0005_driver_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='fastest_lap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fastest_laps', to='sweepstake.Driver'),
        ),
        migrations.AddField(
            model_name='race',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poles', to='sweepstake.Driver'),
        ),
    ]
