# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweepstake', '0006_auto_20180125_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='sweepstake.Driver')),
            ],
        ),
        migrations.AlterField(
            model_name='driverresult',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='sweepstake.Driver'),
        ),
        migrations.AlterField(
            model_name='driverresult',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_results', to='sweepstake.Race'),
        ),
        migrations.AlterField(
            model_name='race',
            name='fastest_lap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sweepstake.PointsValue'),
        ),
        migrations.AlterField(
            model_name='race',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sweepstake.PointsValue'),
        ),
        migrations.AddField(
            model_name='race',
            name='results',
            field=models.ManyToManyField(blank=True, related_query_name='+', to='sweepstake.PointsValue'),
        ),
    ]
