# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweepstake', '0007_auto_20180217_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsvalue',
            name='classified',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='pointsvalue',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
