# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-19 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweepstake', '0008_auto_20180217_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='fastest_lap',
        ),
        migrations.RemoveField(
            model_name='race',
            name='pole',
        ),
        migrations.AddField(
            model_name='pointsvalue',
            name='fastest_lap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointsvalue',
            name='pole',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='race',
            name='results',
            field=models.ManyToManyField(blank=True, related_query_name='race', to='sweepstake.PointsValue'),
        ),
    ]
