# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-20 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sweepstake', '0009_auto_20180219_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drivers', models.ManyToManyField(max_length=3, to='sweepstake.Driver')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='sweepstake.Player')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='sweepstake.Race')),
            ],
        ),
    ]
