# Generated by Django 2.1.1 on 2018-09-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweepstake', '0010_playerselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerselection',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
