# Generated by Django 2.1.1 on 2018-09-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweepstake', '0011_playerselection_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerselection',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
